name: hse-digital-backend
region: nyc

services:
  - name: api
    github:
      repo: your-username/your-repo
      branch: main
      deploy_on_push: true
    build_command: npm install && cd server && npm install && npx prisma generate
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 3001
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
        type: GENERAL
      - key: PORT
        value: "3001"
        scope: RUN_TIME
        type: GENERAL
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: REFRESH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_HOST
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_PORT
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGIN
        scope: RUN_TIME
        type: GENERAL

databases:
  - name: hse-digital-db
    engine: PG
    production: true
    version: "15"
    size: db-s-dev-database

  - name: hse-digital-redis
    engine: REDIS
    production: true
    version: "7"
    size: db-s-dev-database
